
---
title: "First Knit"
author: "David Acevedo"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
  
i attended high school in Palmdale California in Highland High school. I was in Independent Study until the junior year. I did graduate in 2024. but i didnt graduate early. I didn't like either math or English i really enjoyed more of engineering and American Sign Language, but for me English was easier for me than math i had an A+ in English but math i had a C.
     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
  I have a simple Windows laptop at home, im a gamer so i have decent knowledge on the computer and how to work around it and stuff, so I'd say im around a 8 in my knowledge , I also have internet access at home, the internet connection is amazing i never have any lag.
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
  
   Honestly I don't have a preference so id rather just be called by my real name so David is fine with me, my buddies do call me Fat Man sometimes just because its my username on like socials and stuff of that sorts, but everyone can just call me David
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  
   to be honest im still not 100% sure on what i want in life but i do maybe want to one day work at a gaming company.Like maybe SEGA or any other gaming company really but SEGA is my main goal. My degree that i want to go for is a computer science one. Maybe for programming and or coding in general.
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  
   ive never gone to foreign country before. ive also never been out of country, the furthest ive gone is Indiana but other than that that's all. id maybe want to go to Europe because ive heard and seen online that it looks really nice. I don't want to go into the military also because im extremely unhealthy, but if i had to chose a branch maybe coast guard or something. 




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  
   
 im taking math 116, i didnt know that 115 only helps with general education because the reason im taking this class was because of the general education requirements. i plan to get a C or higher in stats so i can pass swiftly and nicely and hope that it would help me transfer to CSUB in the future. 






  




